// error_exit.cpp
#include <iostream>

int main() {
    std::cerr << "Exiting with error!" << std::endl;
    return 1;
}
